// micro-app-react/src/pages/list/index.jsx
import React, { useState, useEffect } from "react";
import { Card, Table, Avatar } from "antd";
import fetch from "isomorphic-fetch";

const fetchVegetable = (page, pageSize) => {
  return fetch("http://dev-api.jt-gmall.com/mall", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    // graphql 的查询风格
    body: JSON.stringify({
      query: `{ vegetableList (page: ${page}, pageSize: ${pageSize}) { page, pageSize, total, items { _id, name, poster, price } } }`,
    }),
  }).then((res) => res.json());
};

const { Column } = Table;
const List = () => {
  // 设置列表信息
  const [data, setData] = useState([]);
  // 设置页码信息
  const [page, setPage] = useState(1);
  const [pageInfo, setPageInfo] = useState();

  useEffect(() => {
    console.log({ page });
    // (async () => {
    //   const result = await fetchVegetable(page, 10);
    //   const { vegetableList } = result.data;
    //   setData(() => vegetableList.items);
    //   setPageInfo(() => ({
    //     current: vegetableList.page,
    //     pageSize: vegetableList.pageSize,
    //     total: vegetableList.total,
    //     onChange: (page) => setPage(page),
    //   }));
    // })();
  }, [page]);

  return (
    <Card title="React 子应用列表页">
      <h2 style={{ fontSize: "26px", color: "#fb4487" }}>
      </h2>
      {/* <Table rowKey="_id" dataSource={data} pagination={pageInfo}>
        <Column dataIndex="poster" render={(text) => <Avatar src={text} />} />
        <Column dataIndex="name" />
        <Column dataIndex="price" render={(text) => <>￥ {text}</>} />
      </Table> */}
    </Card>
  );
};

export default List;

// micro-app-vue/src/pages/list/index.vue
<template>
  <section>
    <a-card title="Vue 微应用列表页">
      <a-table rowKey="_id" :dataSource="data" :pagination="pageInfo">
        <a-table-column title="菜名" dataIndex="name" />
        <a-table-column title="价格" dataIndex="price" :customRender="(text) => `￥ ${text}`" />
      </a-table>
<!--      <h2 class="old-title">曾经充满数据的一个列表（因服务器到期，此处数据已丢失）</h2>-->
    </a-card>
  </section>
</template>

<script>
import fetch from "isomorphic-fetch";

export default {
  name: "List",

  data() {
    return {
      data: [
        {name: "番茄炒鸡蛋",price:12},
        {name: "红烧牛腩",price:30},
      ],
      pageInfo: {
        onChange: page => this.fetchVegetable(page, 10)
      },
    }
  },
  
  methods: {
    async fetchVegetable (page, pageSize) {
      const result = await fetch("http://dev-api.jt-gmall.com/mall", {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        // graphql 的查询风格
        body: JSON.stringify({ query: `{ vegetableList (page: ${page}, pageSize: ${pageSize}) { page, pageSize, total, items { _id, name, poster, price } } }` })
      }).then(res => res.json());
      const { vegetableList } = result.data;
      this.data = vegetableList.items;
      this.pageInfo = {
        current: vegetableList.page,
        pageSize: vegetableList.pageSize,
        total: vegetableList.total,
        onChange: page => this.fetchVegetable(page, 10)
      };
    }
  },

  created() {
    // this.fetchVegetable(1, 10);
  }
}
</script>

<style lang="less" scoped>
.old-title {
  font-size: 26px;
  color: #fb4487;
}
</style>
